// <auto-generated />
using System;
using System.Collections.Generic;
using Agentiva.Risk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentiva.Risk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    partial class RiskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("risk")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("request_type");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_entries");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_key");

                    b.ToTable("idempotency_entries", "risk");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event_consumer");

                    b.ToTable("inbox_messages", "risk");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_event_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("outbox_messages", "risk");
                });

            modelBuilder.Entity("Agentiva.Risk.Domain.Entities.RiskCheckRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_run_id");

                    b.Property<decimal>("ApprovedNotional")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("approved_notional");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("approved_quantity");

                    b.Property<string>("BindingConstraint")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("binding_constraint");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checks_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<decimal>("EffectiveEntryPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("effective_entry_price");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RejectionCodes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_codes");

                    b.Property<decimal>("RiskAmount")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("risk_amount");

                    b.Property<decimal>("RiskBudget")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("risk_budget");

                    b.Property<Guid>("RiskPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_policy_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("take_profit");

                    b.Property<Guid>("TradingIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_intent_id");

                    b.Property<string>("TradingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trading_mode");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_risk_checks");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_risk_checks_correlation");

                    b.HasIndex("EvaluatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_risk_checks_evaluated_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_checks_idempotency_key");

                    b.HasIndex("TradingIntentId")
                        .HasDatabaseName("ix_risk_checks_trading_intent");

                    b.ToTable("risk_checks", "risk");
                });

            modelBuilder.Entity("Agentiva.Risk.Domain.Policies.RiskPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<TimeSpan>("MarketDataStalenessThreshold")
                        .HasColumnType("interval")
                        .HasColumnName("market_data_staleness_threshold");

                    b.Property<decimal>("MaxAssetConcentration")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("max_asset_concentration_percent");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("max_daily_loss_percent");

                    b.Property<int>("MaxOpenPositions")
                        .HasColumnType("integer")
                        .HasColumnName("max_open_positions");

                    b.Property<decimal>("MaxPortfolioExposure")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("max_portfolio_exposure_percent");

                    b.Property<decimal>("MaxRiskPerTrade")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("max_risk_per_trade_percent");

                    b.Property<decimal>("MaxVolatility")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("max_volatility_percent");

                    b.Property<decimal>("MinConfidence")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("min_confidence_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("RequireStopLoss")
                        .HasColumnType("boolean")
                        .HasColumnName("require_stop_loss");

                    b.Property<bool>("RequireTakeProfit")
                        .HasColumnType("boolean")
                        .HasColumnName("require_take_profit");

                    b.Property<decimal>("SlippageAssumption")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("slippage_assumption_percent");

                    b.Property<decimal>("TakerFee")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("taker_fee_percent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MaxPositionNotional", "Agentiva.Risk.Domain.Policies.RiskPolicy.MaxPositionNotional#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(38, 18)
                                .HasColumnType("numeric(38,18)")
                                .HasColumnName("max_position_notional");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("max_position_notional_asset");
                        });

                    b.HasKey("Id")
                        .HasName("pk_risk_policies");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_policies_single_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_policies_name");

                    b.ToTable("risk_policies", "risk");
                });
#pragma warning restore 612, 618
        }
    }
}
