// <auto-generated />
using System;
using Agentiva.Trading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentiva.Trading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trading")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("request_type");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_entries");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_key");

                    b.ToTable("idempotency_entries", "trading");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event_consumer");

                    b.ToTable("inbox_messages", "trading");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_event_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("outbox_messages", "trading");
                });

            modelBuilder.Entity("Agentiva.Trading.Domain.Intents.TradingIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("approved_quantity");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("confidence_percent");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("entry_price");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RejectionCodes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_codes");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid?>("RiskCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_check_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("uuid")
                        .HasColumnName("signal_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("stop_loss");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("take_profit");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.Property<string>("TradingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trading_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_trading_intents");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_trading_intents_correlation");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_trading_intents_created_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_trading_intents_idempotency_key");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_trading_intents_status");

                    b.HasIndex("Symbol", "CreatedAt")
                        .HasDatabaseName("ix_trading_intents_symbol");

                    b.ToTable("trading_intents", "trading");
                });
#pragma warning restore 612, 618
        }
    }
}
