<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Agentiva.Portfolio.Api</RootNamespace>
    <AssemblyName>Agentiva.Portfolio.Api</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>agentiva-portfolio-service</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\building-blocks\Agentiva.BuildingBlocks.ServiceDefaults\Agentiva.BuildingBlocks.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
