// <auto-generated />
using System;
using Agentiva.Backtesting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentiva.Backtesting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BacktestingDbContext))]
    partial class BacktestingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("backtesting")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentiva.Backtesting.Domain.Runs.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<decimal>("FeePercent")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("fee_percent");

                    b.Property<string>("Metrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<decimal>("SlippagePercent")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("slippage_percent");

                    b.Property<decimal>("StartingCapital")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("starting_capital");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strategy_name");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("strategy_version");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("timeframe");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("WalkForwardWindowCount")
                        .HasColumnType("integer")
                        .HasColumnName("walk_forward_window_count");

                    b.Property<string>("WalkForwardWindows")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("walk_forward_windows");

                    b.HasKey("Id")
                        .HasName("pk_backtest_runs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_backtest_runs_created_at");

                    b.ToTable("backtest_runs", "backtesting");
                });

            modelBuilder.Entity("Agentiva.Backtesting.Domain.Runs.BacktestTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BacktestId")
                        .HasColumnType("uuid")
                        .HasColumnName("backtest_id");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("entry_price");

                    b.Property<DateTimeOffset>("EntryTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("entry_time");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exit_reason");

                    b.Property<DateTimeOffset>("ExitTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("exit_time");

                    b.Property<decimal>("Fees")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("fees");

                    b.Property<decimal>("GrossPnl")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("gross_pnl");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCodesJoined")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_codes");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<decimal>("SlippageCost")
                        .HasPrecision(38, 18)
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("slippage_cost");

                    b.HasKey("Id")
                        .HasName("pk_backtest_trades");

                    b.HasIndex("BacktestId", "EntryTime")
                        .HasDatabaseName("ix_backtest_trades_run_entry_time");

                    b.ToTable("backtest_trades", "backtesting");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("request_type");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_entries");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_key");

                    b.ToTable("idempotency_entries", "backtesting");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event_consumer");

                    b.ToTable("inbox_messages", "backtesting");
                });

            modelBuilder.Entity("Agentiva.BuildingBlocks.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_event_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("outbox_messages", "backtesting");
                });

            modelBuilder.Entity("Agentiva.Backtesting.Domain.Runs.BacktestTrade", b =>
                {
                    b.HasOne("Agentiva.Backtesting.Domain.Runs.BacktestRun", null)
                        .WithMany("Trades")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backtest_trades_backtest_runs_backtest_id");
                });

            modelBuilder.Entity("Agentiva.Backtesting.Domain.Runs.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
